name: Deploy para Github Pages
'on':
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Configurar GH Pages
        uses: actions/configure-pages@v5
      - name: Criar artefato para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: index.html
      - name: Publicar no GH Pages
        uses: actions/deploy-pages@v4
